version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "3022"
      POSTGRES_DB: expenses
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=expenses
      - DB_USER=postgres
      - DB_PASSWORD=3022

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://backend:8000
    ports:
      - "3000:3000"
